### ISSUE TITLE
If "font" property doesn't have "font-size" or "font-family" error

### ISSUE THREAD

**Issue by admdh** [jedmao/parse-css-font#1]
using something like this will trough an error
```css
a { font: bold; }
a { font: 12px; }
```
```Error: [parse-css-font] Missing required font-family.```
